name: Chris Fedorcek
favicon: null
layout_spectrum: 0.06014394527301192
typography_spectrum: 0.251346243545413
title: 'Jesus Follower | Husband | Father | Pastor | Blogger'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9bb9eb'
    - '#5f6e34'
    - '#14131b'
    - '#d9c4a9'
  brandStrength: 0.726756494725123
  lightness: 0.2924136780202389
  saturation: 0.2472198004834354
  rhythmicContrast: 0.23423606855794787
purpose: []
